[package]
name = "scroll-grid"
version = "0.1.0"
edition = "2021"

[dependencies]
winit = "0.30.8"
xilem = { git = "https://github.com/linebender/xilem.git", branch = "main" }
masonry = { git = "https://github.com/linebender/xilem.git", branch = "main" }
